name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo code
      uses: actions/checkout@v4
    - name: Setup Node.js latest
      uses: actions/setup-node@v4
      with:
        node-version: latest
        cache: 'npm'
    - name: Start npm
      run: npm run start &
    - name: Run tests
      run: npm run test
