name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo code
      uses: actions/checkout@v4
    - name: Setup Node.js latest
      uses: actions/setup-node@v4
      with:
        node-version: latest
    - name: Security audit
      run: npm audit
    - name: Install npm
      run: npm install
    - name: Start npm
      run: npm start &
    - name: Run tests
      run: npm test
