name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo code
      uses: actions/checkout@v4
    - name: Setup Node.js 20v
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install npm
      run: npm install
    - name: Start back end
      run: npm run start &
    - name: Start front end
      run: npm run server &
    - name: Install Browsers
      run: npx playwright install
    - name: Run tests
      run: npm run test
