name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js v20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Install NPM modules
      run: npm install
    - name: Replace the backend endpoint
      run: echo "export const settings = {host:\"http://localhost:3030\"}" > src/config.js
    - name: Start BackEnd
      run: npm run start-be &
    - name: Start FrontEnd
      run: npm run start-fe &
    - name: Install Browsers
      run: npx playwright install 
    - name: Execute UI tests
      run: npm run test:ui
    - name: Deploy BackEnd on Render
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.RENDER_BACK_END_KEY }}
        api-key: ${{ secrets.RENDER_API_KEY }}
    - name: Deploy FrontEnd on Render
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.RENDER_FRONT_END_KEY }}
        api-key: ${{ secrets.RENDER_API_KEY }}
